version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:

      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique
          - not_null

      - name: host_id
        description: The host's id. references the host table.
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of the apartment/room
        tests:
          - accepted_values:
              values: [ 'Entire home/apt', 'Private room', 'Shared room', 'Hotel room' ]

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
        tests:
          - positive_value

  - name: dim_hosts_cleansed
    description: Cleansed table which contains Airbnb hosts.
    columns:
      - name: host_id
        description: Unique identifier for each host. This is a primary key.
        data_type: number
        tests:
          - not_null
          - unique
      - name: host_name
        description: Name of the host. If the host name is not available, it is replaced with 'Anonymous'.
        data_type: varchar
        tests:
          - not_null
      - name: is_superhost
        description: Boolean flag indicating whether the host is a superhost or not. Superhosts are experienced hosts who provide a shining example for other hosts, and extraordinary experiences for their guests.
        data_type: varchar
        tests:
          - accepted_values:
              values:
                - t
                - f
      - name: created_at
        description: The timestamp when the host record was first created in the Airbnb system.
        data_type: timestamp_ntz
        tests:
          - not_null
      - name: updated_at
        description: The timestamp when the host record was last updated in the Airbnb system.
        data_type: timestamp_ntz

  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb','listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn

  - name: fact_reviews
    description: Reviews for the listings
    columns:
      - name: review_id
        description: A unique identifier for each review. It is generated by concatenating the listing_id, review_date, reviewer_name, and review_text, then applying the MD5 hash function. If any of these fields are null, a placeholder value '_dbt_utils_surrogate_key_null_' is used.
        data_type: varchar
        tests:
          - not_null
      - name: listing_id
        description: This is a unique identifier for each listing on Airbnb. It is a numeric value that is used to uniquely identify each listing.
        data_type: number
        tests:
          - relationships:
              field: LISTING_ID
              to: ref('dim_listings_cleansed')
      - name: review_date
        data_type: timestamp_ntz
      - name: reviewer_name
        description: The name of the individual who wrote the review. This is a string field.
        data_type: varchar
        tests:
          - not_null
      - name: review_text
        description: This column contains the text of the review left by the guest. It is extracted from the 'comments' field in the raw_reviews source table. Null values are excluded from this model.
        data_type: varchar
      - name: review_sentiment
        description: This column contains the sentiment analysis result of the review text. It indicates whether the sentiment of the review is positive, negative, or neutral.
        data_type: varchar
        tests:
          - accepted_values:
              values:
                - positive
                - neutral
                - negative
  - name: mart_fullmoon_reviews
    description: The 'mart_fullmoon_reviews' model is a combination of the 'fact_reviews' and 'seed_full_moon_dates' tables from the AIRBNB.DEV schema. It includes all columns from the 'fact_reviews' table and adds an additional column 'is_full_moon' which indicates whether the review was made on a full moon day or not. The 'is_full_moon' column is determined by joining the 'fact_reviews' table with the 'seed_full_moon_dates' table on the review date.
